version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_DATABASE: 'auth-service'
      MARIADB_USER: 'auth-service-user'
      MARIADB_PASSWORD: 'auth-service-user-password'
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
